version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    restart: always
    ports:
      - "127.0.0.1:5001:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  auth-server:
    build: ./services/auth-server
    command: python project/auth-server.py
    restart: always
    volumes:
      - ./services/auth-server/:/usr/src/app/
    ports:
      - "131.153.57.130:25565:25565"
    env_file:
      - ./.env.prod.auth
  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data_prod:
