version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 --worker-class eventlet -w 1 --threads 20 manage:app
    restart: always
    ports:
      - "127.0.0.1:5001:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - ./services/web/project/static:/home/app/web/project/static
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  auth-server:
    build: ./services/auth-server
    command: python project/auth-server.py
    restart: always
    volumes:
      - ./services/auth-server/:/usr/src/app/
    ports:
      - "131.153.57.130:25565:25565"
    env_file:
      - ./.env.prod.auth
  server-poller:
    build: ./services/server_poller
    command: python project/server_poller.py
    volumes:
      - ./services/server_poller/:/usr/src/app/
    env_file:
      - ./.env.prod
  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data_prod:
