"""Character activity

Revision ID: 0ac0a93ccad1
Revises: cc9ce76cd215
Create Date: 2022-05-12 15:54:34.861293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac0a93ccad1'
down_revision = 'cc9ce76cd215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE characters SET is_active = true")
    op.alter_column('characters', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_active')
    # ### end Alembic commands ###
