"""Add webhook settings

Revision ID: 0dec22d2616a
Revises: 5f46b490a9ac
Create Date: 2022-09-16 22:58:01.222917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dec22d2616a'
down_revision = '5f46b490a9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('ticket_webhook', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('application_webhook', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('general_webhook', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('dev_webhook', sa.String(length=255), nullable=True))
    # Set the default for all new columns to CHANGE_ME
    op.execute("UPDATE system_settings SET ticket_webhook = 'CHANGE_ME'")
    op.execute("UPDATE system_settings SET application_webhook = 'CHANGE_ME'")
    op.execute("UPDATE system_settings SET general_webhook = 'CHANGE_ME'")
    op.execute("UPDATE system_settings SET dev_webhook = 'CHANGE_ME'")
    # Set them back to nullable=False
    op.alter_column('system_settings', 'ticket_webhook', nullable=False)
    op.alter_column('system_settings', 'application_webhook', nullable=False)
    op.alter_column('system_settings', 'general_webhook', nullable=False)
    op.alter_column('system_settings', 'dev_webhook', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'dev_webhook')
    op.drop_column('system_settings', 'general_webhook')
    op.drop_column('system_settings', 'application_webhook')
    op.drop_column('system_settings', 'ticket_webhook')
    # ### end Alembic commands ###
