"""Application faction id

Revision ID: 1549e4b646fe
Revises: bfdea9ecc4db
Create Date: 2022-04-12 19:04:54.691762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1549e4b646fe'
down_revision = 'bfdea9ecc4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('character_faction_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'factions', ['character_faction_id'], ['id'])
    op.drop_column('applications', 'character_faction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('character_faction', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'character_faction_id')
    # ### end Alembic commands ###
