"""New user fields

Revision ID: 16e8c1f8993e
Revises: 73e7c04dd323
Create Date: 2022-04-29 15:17:37.443590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e8c1f8993e'
down_revision = '73e7c04dd323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('staff_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('staff_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_title')
    op.drop_column('users', 'staff_notes')
    op.drop_column('users', 'ban_reason')
    # ### end Alembic commands ###
