"""Join discord on register

Revision ID: 2f34ede5bc14
Revises: 43034be2bc98
Create Date: 2022-09-04 19:54:15.899218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f34ede5bc14'
down_revision = '43034be2bc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('join_discord_on_register', sa.Boolean(), nullable=True))
    op.execute("UPDATE system_settings SET join_discord_on_register = false")
    op.alter_column('system_settings', 'join_discord_on_register', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'join_discord_on_register')
    # ### end Alembic commands ###
