"""Add commands to factions

Revision ID: 39852168ed51
Revises: 3f2b2832e673
Create Date: 2022-09-19 03:35:35.972839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39852168ed51'
down_revision = '3f2b2832e673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factions', sa.Column('commands', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factions', 'commands')
    # ### end Alembic commands ###
