"""Applications open

Revision ID: 3e7cafc41f05
Revises: 8d8790ee91c8
Create Date: 2022-04-12 18:26:19.005781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7cafc41f05'
down_revision = '8d8790ee91c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('applications_open', sa.Boolean(), nullable=False))
    op.drop_column('system_settings', 'value')
    op.drop_column('system_settings', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('system_settings', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('system_settings', 'applications_open')
    # ### end Alembic commands ###
