"""Add commands to race and clas

Revision ID: 3f2b2832e673
Revises: 0dec22d2616a
Create Date: 2022-09-19 03:16:28.392099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2b2832e673'
down_revision = '0dec22d2616a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('commands', sa.Text(), nullable=True))
    op.add_column('races', sa.Column('commands', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'commands')
    op.drop_column('classes', 'commands')
    # ### end Alembic commands ###
