"""Server status

Revision ID: 406cdf7b4990
Revises: 3383ded1e55c
Create Date: 2022-05-05 13:11:37.930836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '406cdf7b4990'
down_revision = '3383ded1e55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_status',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_status')
    # ### end Alembic commands ###
