"""Add application settings

Revision ID: 43034be2bc98
Revises: 401d2fcbe9e4
Create Date: 2022-09-04 19:50:51.555555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43034be2bc98'
down_revision = '401d2fcbe9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('minimum_length', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('maximum_length', sa.Integer(), nullable=True))
    # Set min to 20 and max to 10000
    op.execute("UPDATE system_settings SET minimum_length = 20, maximum_length = 10000")
    # Set nullable to false
    op.alter_column('system_settings', 'minimum_length', nullable=False)
    op.alter_column('system_settings', 'maximum_length', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'maximum_length')
    op.drop_column('system_settings', 'minimum_length')
    # ### end Alembic commands ###
