"""Timestamps

Revision ID: 5284fcbf29d7
Revises: 8eb5a32c5b0a
Create Date: 2022-04-10 20:15:45.068240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5284fcbf29d7'
down_revision = '8eb5a32c5b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('characters', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'updated_at')
    op.drop_column('characters', 'created_at')
    # ### end Alembic commands ###
