"""Add faction to race and class

Revision ID: 5f46b490a9ac
Revises: 2f34ede5bc14
Create Date: 2022-09-15 23:24:00.383012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f46b490a9ac'
down_revision = '2f34ede5bc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('faction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'factions', ['faction_id'], ['id'])
    op.add_column('races', sa.Column('faction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'races', 'factions', ['faction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_column('races', 'faction_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'faction_id')
    # ### end Alembic commands ###
