"""Ticket department options

Revision ID: 76cfd417f955
Revises: 357ff9521d80
Create Date: 2022-04-12 13:15:39.942673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cfd417f955'
down_revision = '357ff9521d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_departments', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.add_column('ticket_departments', sa.Column('is_disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_departments', 'is_disabled')
    op.drop_column('ticket_departments', 'is_hidden')
    # ### end Alembic commands ###
