"""Adding characters

Revision ID: 8eb5a32c5b0a
Revises: eb6385ff735f
Create Date: 2022-04-10 20:05:46.712079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb5a32c5b0a'
down_revision = 'eb6385ff735f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faction', sa.String(length=255), nullable=False),
    sa.Column('subrace', sa.String(length=255), nullable=False),
    sa.Column('clazz', sa.String(length=255), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starting_power', sa.JSON(), nullable=False),
    sa.Column('is_permad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
