"""Factions but fixed

Revision ID: 8f26d40bbe76
Revises: 58afc5450eea
Create Date: 2022-04-12 18:42:40.788155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f26d40bbe76'
down_revision = '58afc5450eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'faction')
    op.add_column('characters', sa.Column('faction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'factions', ['faction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    # ### end Alembic commands ###
