"""More system settings

Revision ID: 9291a45801f6
Revises: 16e8c1f8993e
Create Date: 2022-04-29 15:26:19.096613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9291a45801f6'
down_revision = '16e8c1f8993e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set all these columns to nullable and then set their default values
    op.add_column('system_settings', sa.Column('panel_api_key', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('live_server_uuid', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('staging_server_uuid', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('fallback_server_uuid', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('maintenance_mode', sa.Boolean(), nullable=True))
    op.execute("UPDATE system_settings SET panel_api_key = 'CHANGE_ME', live_server_uuid = 'CHANGE_ME', staging_server_uuid = 'CHANGE_ME', fallback_server_uuid = 'CHANGE_ME', maintenance_mode = false")
    # Set nullable back to false
    op.alter_column('system_settings', 'panel_api_key', nullable=False)
    op.alter_column('system_settings', 'live_server_uuid', nullable=False)
    op.alter_column('system_settings', 'staging_server_uuid', nullable=False)
    op.alter_column('system_settings', 'fallback_server_uuid', nullable=False)
    op.alter_column('system_settings', 'maintenance_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'maintenance_mode')
    op.drop_column('system_settings', 'fallback_server_uuid')
    op.drop_column('system_settings', 'staging_server_uuid')
    op.drop_column('system_settings', 'live_server_uuid')
    op.drop_column('system_settings', 'panel_api_key')
    # ### end Alembic commands ###
