"""Application user id

Revision ID: 92db3807b175
Revises: 1549e4b646fe
Create Date: 2022-04-12 19:28:25.687663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db3807b175'
down_revision = '1549e4b646fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('applications_user_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    op.drop_column('applications', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_user_fkey', 'applications', 'users', ['user'], ['id'])
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
