"""Ticket status

Revision ID: ab018b9414d3
Revises: 76cfd417f955
Create Date: 2022-04-12 13:42:23.663961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab018b9414d3'
down_revision = '76cfd417f955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(length=255), nullable=True))
    op.execute("UPDATE tickets SET status = 'open'")
    op.alter_column('tickets', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
