"""Adding auth

Revision ID: ac5e9a2e3fb5
Revises: 5a589787fdd9
Create Date: 2022-04-10 01:55:00.017327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5e9a2e3fb5'
down_revision = '5a589787fdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minecraft_authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_code', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('character_name', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('character_faction', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('character_race', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('character_class', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('backstory', sa.Text(), nullable=False))
    op.add_column('applications', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('applications', 'discord_username')
    op.drop_column('applications', 'bio')
    op.drop_column('applications', 'race')
    op.drop_column('applications', 'sub_race')
    op.drop_column('applications', 'minecraft_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('minecraft_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('sub_race', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('race', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('discord_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('applications', 'description')
    op.drop_column('applications', 'backstory')
    op.drop_column('applications', 'character_class')
    op.drop_column('applications', 'character_race')
    op.drop_column('applications', 'character_faction')
    op.drop_column('applications', 'character_name')
    op.drop_table('minecraft_authentications')
    # ### end Alembic commands ###
