"""Application cooldown and rejection reason

Revision ID: b29fd381adaf
Revises: 92db3807b175
Create Date: 2022-04-12 23:10:34.555777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29fd381adaf'
down_revision = '92db3807b175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('cooldown', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cooldown')
    op.drop_column('applications', 'rejection_reason')
    # ### end Alembic commands ###
