"""Disable registration

Revision ID: d9c32361e027
Revises: f2762043d0f4
Create Date: 2022-05-27 15:59:34.371471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c32361e027'
down_revision = 'f2762043d0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('can_register', sa.Boolean(), nullable=True))
    op.execute("UPDATE system_settings SET can_register = false")
    op.alter_column('system_settings', 'can_register', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'can_register')
    # ### end Alembic commands ###
