"""Psych

Revision ID: ddf331087a1a
Revises: 2d7e69843959
Create Date: 2022-04-12 16:12:00.144500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf331087a1a'
down_revision = '2d7e69843959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('last_replied_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE tickets SET last_replied_at = (SELECT MAX(created_at) FROM ticket_replies WHERE ticket_id = tickets.id)")
    op.alter_column('tickets', 'last_replied_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'last_replied_at')
    # ### end Alembic commands ###
