"""Site theme per user

Revision ID: e73842c57ec7
Revises: 8e8ba38bf52e
Create Date: 2022-04-16 16:03:50.623816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73842c57ec7'
down_revision = '8e8ba38bf52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_theme', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'site_theme')
    # ### end Alembic commands ###
