"""Character scale

Revision ID: f2762043d0f4
Revises: 0ac0a93ccad1
Create Date: 2022-05-12 17:08:43.810536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2762043d0f4'
down_revision = '0ac0a93ccad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('character_scale', sa.String(length=255), nullable=True))
    op.add_column('characters', sa.Column('scale', sa.String(length=255), nullable=True))
    op.execute("UPDATE applications SET character_scale = '0'")
    op.execute("UPDATE characters SET scale = '0'")
    op.alter_column('applications', 'character_scale', nullable=False)
    op.alter_column('characters', 'scale', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'scale')
    op.drop_column('applications', 'character_scale')
    # ### end Alembic commands ###
