"""Unique session ID

Revision ID: f5775ba480ab
Revises: b29fd381adaf
Create Date: 2022-04-14 16:58:08.789914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5775ba480ab'
down_revision = 'b29fd381adaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True))
    # Generate a random UUID for each user
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute("UPDATE users SET session_id = uuid_generate_v4()")
    op.alter_column('users', 'session_id', nullable=False)
    op.create_unique_constraint(None, 'users', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
